import { filterBarMarkup } from './filter.js';

export function createOverlayShell(options = {}) {
    const doc = options.document || document;
    const overlay = doc.createElement('div');
    const classes = Array.isArray(options.classes) ? options.classes.filter(Boolean) : [];
    overlay.className = ['ms-gallery-overlay'].concat(classes).join(' ');
    if (options.fontFamily) overlay.style.fontFamily = options.fontFamily;

    overlay.innerHTML = [
        '<div class="ms-gallery-topbar">',
        '  <div class="ms-gallery-info"></div>',
        '  <div class="ms-gallery-center">',
        '    <label class="ms-position-control" title="Go to image"><input type="text" inputmode="numeric" pattern="[0-9]*" class="ms-index-input" value="1" aria-label="Go to image"><span aria-hidden="true">/</span><span class="ms-position-total">1</span></label>',
        '    <div class="ms-topbar-spinner" title="Loading full image..."></div>',
        '    <button class="ms-btn ms-icon-btn ms-fullscreen-btn" data-act="fullscreen-toggle" title="Fit to page"><svg viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3"/></svg></button>',
        '    <button class="ms-btn ms-icon-btn ms-fav-btn" data-act="fav-toggle" style="display:none;" title="Favorite"><svg viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78z"/></svg></button>',
        '    <button class="ms-btn ms-icon-btn ms-x-action" data-act="x-like" style="display:none;" title="Like post"><svg viewBox="0 0 24 24"><path d="M16.7 5.5c-1.3 0-2.7.6-3.9 2.2L12 8.8l-.8-1.1C10 6.1 8.6 5.5 7.3 5.5 5 5.6 3.4 7.8 4.4 10.4c.8 2.2 3.2 5.3 7.6 8 4.4-2.7 6.8-5.8 7.6-8 1-2.6-.6-4.8-2.9-4.9Z"/></svg></button>',
        '    <button class="ms-btn ms-icon-btn ms-x-action" data-act="x-bookmark" style="display:none;" title="Bookmark post"><svg viewBox="0 0 24 24"><path d="M6.5 3h11c.8 0 1.5.7 1.5 1.5V21l-7-5-7 5V4.5C5 3.7 5.7 3 6.5 3Z"/></svg></button>',
        '    <div class="ms-zoom-slider-wrap ms-zoom-idle">',
        '      <b class="ms-zoom-value"></b>',
        '      <input type="range" class="ms-zoom-slider" min="0.1" max="3" step="0.01">',
        '    </div>',
        '  </div>',
        '  <div class="ms-gallery-controls">',
        '    <button class="ms-btn ms-hd-btn" data-act="hd" style="display:none;"><span class="ms-hd-spinner"></span>HD</button>',
        '    <button class="ms-btn ms-tags-btn" data-act="show-tags" style="display:' + (options.showInfo ? '' : 'none') + ';"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.59 13.41L13.42 20.58a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><circle cx="7" cy="7" r="1.5"/></svg><span class="ms-btn-label">' + String(options.infoLabel || 'Tags') + '</span></button>',
        '    <button class="ms-btn ms-loop-btn" data-act="loop-toggle" style="display:none;" title="Loop"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 1l4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="M7 23l-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg><span class="ms-btn-label">Loop</span></button>',
        '    <button class="ms-btn ms-filter-trigger" data-act="filter-toggle" aria-expanded="false" title="Filter gallery"><svg class="ms-btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 5H3"/><path d="M12 19H3"/><path d="M14 3v4"/><path d="M16 17v4"/><path d="M21 12h-9"/><path d="M21 19h-5"/><path d="M21 5h-7"/><path d="M8 10v4"/><path d="M8 12H3"/></svg><span class="ms-btn-label">FILTER</span></button>',
        '    <button class="ms-btn" data-act="view-toggle"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span class="ms-btn-label">Grid</span></button>',
        '    <button class="ms-btn" data-act="pan-toggle" title="Zoom &amp; pan"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.35-4.35"/></svg><span class="ms-btn-label">Zoom</span></button>',
        '    <button class="ms-btn" data-act="download" title="Download"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12"/><path d="M7 11l5 5 5-5"/><path d="M4 20h16"/></svg><span class="ms-btn-label">DL</span></button>',
        '    <div class="ms-dropdown">',
        '      <button class="ms-btn ms-dropdown-trigger" data-act="fit-trigger"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18"/><path d="M8 7l4-4 4 4"/><path d="M8 17l4 4 4-4"/></svg><span class="ms-btn-label">Fit: Std</span></button>',
        '      <div class="ms-dropdown-menu">',
        '    <button class="ms-dropdown-item" data-act="fit" data-val="standard">Standard</button>',
        '    <button class="ms-dropdown-item" data-act="fit" data-val="vertical">Vertical</button>',
        '      </div>',
        '    </div>',
        '    <button class="ms-btn" data-act="thumbs-toggle" title="Toggle thumbnails"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="5.5" height="10" rx="1"/><rect x="9.25" y="7" width="5.5" height="10" rx="1"/><rect x="16.5" y="7" width="5.5" height="10" rx="1"/></svg><span class="ms-btn-label">Thumbs</span></button>',
        '    <button class="ms-btn ms-close-btn" data-act="close" title="Close"><svg class="ms-btn-icon" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6L6 18"/><path d="M6 6l12 12"/></svg><span class="ms-btn-label">Close</span></button>',
        '  </div>',
        '</div>',
        filterBarMarkup(),
        '<div class="ms-gallery-stage">',
        '  <div class="ms-tags-overlay">',
        '    <div class="ms-tags-panel">',
        '      <div class="ms-tags-header">',
        '    <h3>Image Tags</h3>',
        '    <div class="ms-tags-header-tools">',
        '      <button class="ms-tags-font-btn" data-act="tags-font" data-val="-1" title="Smaller text">A&minus;</button>',
        '      <button class="ms-tags-font-btn" data-act="tags-font" data-val="1" title="Larger text">A+</button>',
        '      <button class="ms-tags-close" data-act="tags-close">&times;</button>',
        '    </div>',
        '      </div>',
        '      <div class="ms-tags-content"></div>',
        '    </div>',
        '    <div class="ms-tags-resizer" title="Drag to resize"></div>',
        '  </div>',
        '  <button class="ms-nav prev" data-act="prev" aria-label="Previous image"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg></button>',
        '  <div class="ms-media-wrap"></div>',
        '  <button class="ms-nav next" data-act="next" aria-label="Next image"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></button>',
        '</div>',
        '<div class="ms-reddit-info-row">',
        '  <div class="ms-reddit-card">',
        '    <div class="ms-reddit-resizer" title="Drag to resize"></div>',
        '    <div class="ms-reddit-postinfo">',
        '      <a class="ms-reddit-title" target="_blank" rel="noopener" href="#"></a>',
        '      <div class="ms-reddit-meta"></div>',
        '    </div>',
        '  </div>',
        '  <div class="ms-reddit-actions">',
        '    <div class="ms-reddit-votes">',
        '      <button class="ms-reddit-vote" data-rdvote="upvote" title="Upvote"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 3l8 9h-5v9H9v-9H4z"/></svg></button>',
        '      <span class="ms-reddit-score">&#8226;</span>',
        '      <button class="ms-reddit-vote" data-rdvote="downvote" title="Downvote"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 21l-8-9h5V3h6v9h5z"/></svg></button>',
        '    </div>',
        '    <button class="ms-reddit-save" data-rdsave="1" title="Save post"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M6 2h12a1 1 0 0 1 1 1v19l-7-4.5L5 22V3a1 1 0 0 1 1-1z"/></svg><span class="ms-reddit-save-label">Save</span></button>',
        '  </div>',
        '</div>',
        '<div class="ms-grid-wrap"><div class="ms-grid"></div><button type="button" class="ms-grid-loadmore">Load more</button></div>',
        '<div class="ms-grid-controls"><span>Thumb size <b class="ms-grid-size-value"></b></span><input type="range" class="ms-grid-size-slider" min="90" max="340" step="10"></div>',
        '<div class="ms-thumbs-wrap"><div class="ms-thumbs-track"></div></div>'
    ].join('');

    return overlay;
}
